(function() {var implementors = {};
implementors["handlebars_iron"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"handlebars_iron/struct.HandlebarsEngine.html\" title=\"struct handlebars_iron::HandlebarsEngine\">HandlebarsEngine</a>",synthetic:true,types:["handlebars_iron::middleware::HandlebarsEngine"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"handlebars_iron/struct.Template.html\" title=\"struct handlebars_iron::Template\">Template</a>",synthetic:true,types:["handlebars_iron::middleware::Template"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"handlebars_iron/struct.SourceError.html\" title=\"struct handlebars_iron::SourceError\">SourceError</a>",synthetic:true,types:["handlebars_iron::source::SourceError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"handlebars_iron/struct.DirectorySource.html\" title=\"struct handlebars_iron::DirectorySource\">DirectorySource</a>",synthetic:true,types:["handlebars_iron::sources::directory::DirectorySource"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"handlebars_iron/struct.MemorySource.html\" title=\"struct handlebars_iron::MemorySource\">MemorySource</a>",synthetic:true,types:["handlebars_iron::sources::memory::MemorySource"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
